# This is a basic workflow to help you get started with Actions

name: release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set version.yml version to branch
      run: echo ::set-env name=versionToBranch::$(grep 'version:' version.yml | awk '{print $2}')
    - name: Create local changes
      run: |
        xargs rm -rf <remove-private.txt
        xargs rm -rf remove-private.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "new public repo" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: christianhilbrands/public
        branch: ${{ env.versionToBranch }}
        github_token: ${{ secrets.ACCESS_TOKEN }}
        force: true
